runtime: python
env: flex
entrypoint: gunicorn -b :$PORT project1.wsgi
handlers:
- url: /static
  static_dir: static/
- url: .*
  script: auto
- url: /files
  static_files: files/.*
  upload: static/.*
runtime_config:
  python_version: 3