# Generated by Django 2.1.5 on 2020-01-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seperate', '0002_auto_20200120_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydb',
            name='name',
            field=models.TextField(),
        ),
    ]
