# Generated by Django 2.1.5 on 2020-01-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seperate', '0003_auto_20200120_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydb',
            name='id',
            field=models.IntegerField(null=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mydb',
            name='name',
            field=models.TextField(null=0),
        ),
        migrations.AlterField(
            model_name='mydb',
            name='title',
            field=models.TextField(null=0),
        ),
    ]
