# Generated by Django 2.1.5 on 2020-01-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seperate', '0004_auto_20200120_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydb',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mydb',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mydb',
            name='title',
            field=models.TextField(),
        ),
    ]
