# Generated by Django 2.1.5 on 2020-01-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seperate', '0005_auto_20200120_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydb',
            name='id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
