# Generated by Django 2.1.5 on 2020-01-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seperate', '0006_auto_20200120_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_excel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.FileField(upload_to='excel')),
            ],
        ),
        migrations.DeleteModel(
            name='myDB',
        ),
    ]
