# Generated by Django 2.1.5 on 2020-01-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seperate', '0008_auto_20200120_1615'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload_pkl',
        ),
    ]
