# Generated by Django 2.1.5 on 2020-01-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seperate', '0010_upload_pkl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_pkl',
            name='category',
            field=models.FileField(upload_to=''),
        ),
    ]
